<?php

namespace ContainerCG7bm7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6eo6sQHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6eo6sQH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6eo6sQH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'provider' => ['privates', '.errored..service_locator.6eo6sQH.App\\Entity\\Provider', NULL, 'Cannot autowire service ".service_locator.6eo6sQH": it needs an instance of "App\\Entity\\Provider" but this type has been excluded in "config/services.yaml".'],
            'providerRepository' => ['privates', 'App\\Repository\\ProviderRepository', 'getProviderRepositoryService', true],
        ], [
            'provider' => 'App\\Entity\\Provider',
            'providerRepository' => 'App\\Repository\\ProviderRepository',
        ]);
    }
}
