<?php

namespace ContainerCG7bm7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VXJivNXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VXJivNX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VXJivNX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'provider' => ['privates', '.errored..service_locator.VXJivNX.App\\Entity\\Provider', NULL, 'Cannot autowire service ".service_locator.VXJivNX": it needs an instance of "App\\Entity\\Provider" but this type has been excluded in "config/services.yaml".'],
        ], [
            'provider' => 'App\\Entity\\Provider',
        ]);
    }
}
