<?php

namespace ContainerCG7bm7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BPnKN7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bPn_kN7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bPn_kN7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'providerRepository' => ['privates', 'App\\Repository\\ProviderRepository', 'getProviderRepositoryService', true],
        ], [
            'providerRepository' => 'App\\Repository\\ProviderRepository',
        ]);
    }
}
