<?php

namespace ContainerCG7bm7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OT9pr5NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oT9pr5N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oT9pr5N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ArticleController::delete' => ['privates', '.service_locator.tOLlTpj', 'get_ServiceLocator_TOLlTpjService', true],
            'App\\Controller\\ArticleController::edit' => ['privates', '.service_locator.tOLlTpj', 'get_ServiceLocator_TOLlTpjService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\ArticleController::new' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.XqCCpgA', 'get_ServiceLocator_XqCCpgAService', true],
            'App\\Controller\\ProviderController::delete' => ['privates', '.service_locator.6eo6sQH', 'get_ServiceLocator_6eo6sQHService', true],
            'App\\Controller\\ProviderController::edit' => ['privates', '.service_locator.6eo6sQH', 'get_ServiceLocator_6eo6sQHService', true],
            'App\\Controller\\ProviderController::index' => ['privates', '.service_locator.bPn_kN7', 'get_ServiceLocator_BPnKN7Service', true],
            'App\\Controller\\ProviderController::new' => ['privates', '.service_locator.bPn_kN7', 'get_ServiceLocator_BPnKN7Service', true],
            'App\\Controller\\ProviderController::show' => ['privates', '.service_locator.VXJivNX', 'get_ServiceLocator_VXJivNXService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.UUMJOv4', 'get_ServiceLocator_UUMJOv4Service', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.920S.Ym', 'get_ServiceLocator_920S_YmService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.EE0.cm9', 'get_ServiceLocator_EE0_Cm9Service', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.Z9ydiC1', 'get_ServiceLocator_Z9ydiC1Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ArticleController:delete' => ['privates', '.service_locator.tOLlTpj', 'get_ServiceLocator_TOLlTpjService', true],
            'App\\Controller\\ArticleController:edit' => ['privates', '.service_locator.tOLlTpj', 'get_ServiceLocator_TOLlTpjService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\ArticleController:new' => ['privates', '.service_locator.b12wXHr', 'get_ServiceLocator_B12wXHrService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.XqCCpgA', 'get_ServiceLocator_XqCCpgAService', true],
            'App\\Controller\\ProviderController:delete' => ['privates', '.service_locator.6eo6sQH', 'get_ServiceLocator_6eo6sQHService', true],
            'App\\Controller\\ProviderController:edit' => ['privates', '.service_locator.6eo6sQH', 'get_ServiceLocator_6eo6sQHService', true],
            'App\\Controller\\ProviderController:index' => ['privates', '.service_locator.bPn_kN7', 'get_ServiceLocator_BPnKN7Service', true],
            'App\\Controller\\ProviderController:new' => ['privates', '.service_locator.bPn_kN7', 'get_ServiceLocator_BPnKN7Service', true],
            'App\\Controller\\ProviderController:show' => ['privates', '.service_locator.VXJivNX', 'get_ServiceLocator_VXJivNXService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.UUMJOv4', 'get_ServiceLocator_UUMJOv4Service', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.920S.Ym', 'get_ServiceLocator_920S_YmService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.EE0.cm9', 'get_ServiceLocator_EE0_Cm9Service', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.Z9ydiC1', 'get_ServiceLocator_Z9ydiC1Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ArticleController::delete' => '?',
            'App\\Controller\\ArticleController::edit' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ArticleController::new' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'App\\Controller\\ProviderController::delete' => '?',
            'App\\Controller\\ProviderController::edit' => '?',
            'App\\Controller\\ProviderController::index' => '?',
            'App\\Controller\\ProviderController::new' => '?',
            'App\\Controller\\ProviderController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ArticleController:delete' => '?',
            'App\\Controller\\ArticleController:edit' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ArticleController:new' => '?',
            'App\\Controller\\ArticleController:show' => '?',
            'App\\Controller\\ProviderController:delete' => '?',
            'App\\Controller\\ProviderController:edit' => '?',
            'App\\Controller\\ProviderController:index' => '?',
            'App\\Controller\\ProviderController:new' => '?',
            'App\\Controller\\ProviderController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
