<?php

namespace ContainerCG7bm7E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6eo6sQH.App\Entity\Provider' shared service.
     *
     * @return \App\Entity\Provider
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6eo6sQH": it needs an instance of "App\\Entity\\Provider" but this type has been excluded in "config/services.yaml".');
    }
}
